/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Sistema;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    private final Modelo modelo;
    private Controlador controlador;
    
    public Vista(Modelo modelo) {
        this.modelo = modelo;
        initComponents();
        asignarEventos();
        this.setVisible(true);
    }
    
    public Modelo getModelo()
    {
        return modelo;
    }
    
    public Controlador getControlador()
    {
        if(controlador == null)
        {
            controlador=new Controlador(this);
        }
        return controlador;
    }
    
    public void asignarEventos()
    {
        this.jBPlay.addActionListener(this.getControlador());
        this.jBAvanzar.addActionListener(this.getControlador());
        this.jBGiroIzq.addActionListener(this.getControlador());
        this.jBGiroDer.addActionListener(this.getControlador());
        this.jBEncender.addActionListener(this.getControlador());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTablero = new javax.swing.JPanel();
        jBPlay = new javax.swing.JButton();
        jPOpciones = new javax.swing.JPanel();
        jBAvanzar = new javax.swing.JButton();
        jBGiroIzq = new javax.swing.JButton();
        jBGiroDer = new javax.swing.JButton();
        jBEncender = new javax.swing.JButton();
        jPSecuencia = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPTablero.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPTableroLayout = new javax.swing.GroupLayout(jPTablero);
        jPTablero.setLayout(jPTableroLayout);
        jPTableroLayout.setHorizontalGroup(
            jPTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPTableroLayout.setVerticalGroup(
            jPTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );

        jBPlay.setText("Play");

        jBAvanzar.setText("Avanzar");

        jBGiroIzq.setText("Girar Izq");

        jBGiroDer.setText("Girar Der");

        jBEncender.setText("Encender");
        jBEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEncenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPOpcionesLayout = new javax.swing.GroupLayout(jPOpciones);
        jPOpciones.setLayout(jPOpcionesLayout);
        jPOpcionesLayout.setHorizontalGroup(
            jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jBAvanzar)
                .addGap(18, 18, 18)
                .addComponent(jBGiroIzq)
                .addGap(18, 18, 18)
                .addComponent(jBGiroDer)
                .addGap(18, 18, 18)
                .addComponent(jBEncender)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPOpcionesLayout.setVerticalGroup(
            jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAvanzar)
                    .addComponent(jBGiroIzq)
                    .addComponent(jBGiroDer)
                    .addComponent(jBEncender))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPSecuenciaLayout = new javax.swing.GroupLayout(jPSecuencia);
        jPSecuencia.setLayout(jPSecuenciaLayout);
        jPSecuenciaLayout.setHorizontalGroup(
            jPSecuenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPSecuenciaLayout.setVerticalGroup(
            jPSecuenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 215, Short.MAX_VALUE))
                    .addComponent(jPSecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPSecuencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEncenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBEncenderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAvanzar;
    private javax.swing.JButton jBEncender;
    private javax.swing.JButton jBGiroDer;
    private javax.swing.JButton jBGiroIzq;
    private javax.swing.JButton jBPlay;
    private javax.swing.JPanel jPOpciones;
    private javax.swing.JPanel jPSecuencia;
    private javax.swing.JPanel jPTablero;
    // End of variables declaration//GEN-END:variables
    
    //Metodos Get y Set de los componenetes de la vista
    
    
    public JPanel getjPanel1() {
        return jPTablero;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPTablero = jPanel1;
    }

    public JButton getjBAvanzar() {
        return jBAvanzar;
    }

    public void setjBAvanzar(JButton jBAvanzar) {
        this.jBAvanzar = jBAvanzar;
    }

    public JButton getjBEncender() {
        return jBEncender;
    }

    public void setjBEncender(JButton jBEncender) {
        this.jBEncender = jBEncender;
    }

    public JButton getjBGiroDer() {
        return jBGiroDer;
    }

    public void setjBGiroDer(JButton jBGiroDer) {
        this.jBGiroDer = jBGiroDer;
    }

    public JButton getjBGiroIzq() {
        return jBGiroIzq;
    }

    public void setjBGiroIzq(JButton jBGiroIzq) {
        this.jBGiroIzq = jBGiroIzq;
    }

    public JButton getjBPlay() {
        return jBPlay;
    }

    public void setjBPlay(JButton jBPlay) {
        this.jBPlay = jBPlay;
    }

    public JPanel getjPOpciones() {
        return jPOpciones;
    }

    public void setjPOpciones(JPanel jPOpciones) {
        this.jPOpciones = jPOpciones;
    }

    public JPanel getjPSecuencia() {
        return jPSecuencia;
    }

    public void setjPSecuencia(JPanel jPSecuencia) {
        this.jPSecuencia = jPSecuencia;
    }

    public JPanel getjPTablero() {
        return jPTablero;
    }

    public void setjPTablero(JPanel jPTablero) {
        this.jPTablero = jPTablero;
    }
    
    
    
}
